### DISCUSSION TITLE
/blog/running-gemma-4-26b-a4b-locally/

### DISCUSSION THREAD

**Discussion by giscus** [carteakey/carteakey.dev#91] [Announcements]
# /blog/running-gemma-4-26b-a4b-locally/

End-to-end Gemma 4 setup on mainline llama.cpp with text and vision throughput notes.

https://carteakey.dev/blog/running-gemma-4-26b-a4b-locally/

**Comment by duncancmcleod97** [comment]
Hey, i've been running this same model on the same amount of VRAM with similar settings on llama.cpp but i seem to always encounter a CUDA error or looping word error. Any advice on how to fix this?
Here's my config (more or less; I'm always changing things around to test)
    -c 70000 ^
    -ngl 999 ^
    --n-cpu-moe 18 ^
    --temp 1.0 ^
    -t 16 ^
    --top-k 20 ^
    --batch-size 1024 ^
    --ubatch-size 512 ^
    --top-p 0.95 ^
    --min-p 0 ^
    --presence-penalty 1.5 ^
    --repeat-penalty 1.0 ^
    --host 0.0.0.0 ^
    --port 8080 ^
    --verbose

**Reply by carteakey** [reply]
hey, I can recommend some things you can try 

- your params look fine, except the n cpu moe may be too less? try bumping that up to 22, 24
- have you tried using fit and fit-target instead? It should theoretically leave you a bit more headroom with VRAM.
- For looping error you should use the latest llama.cpp and chat template. 
- llama.cpp had SO many fixes to fix looping issues, try building latest and use the `--chat-template-file /models/gemma4/gemma4_chat_template_26B.jinja` (or redownload the model)
- Don't use cuda 13.2 as its supposedly having issues (check using nvcc --version)

**Comment by alaa-alawi** [comment]
Hey, appreciate the effort, really it spiked my excitement to try gemma4-26b-a4a on my 12gb card!
I have an RTX 3060 with 12gb vram, I compiled the latest llama.cpp (git pulled it today), and it compiled fine. However trying to run it i ran into the following error, and I tried several times and I do not know what I'm missing or messed up? is there is something else to try?

ggml_cuda_compute_forward: SCALE failed
CUDA error: no kernel image is available for execution on the device
  current device: 0, in function ggml_cuda_compute_forward at /home/alaa/src/llama.cpp/ggml/src/ggml-cuda/ggml-cuda.cu:2962
  err
/home/alaa/src/llama.cpp/ggml/src/ggml-cuda/ggml-cuda.cu:97: CUDA error
[New LWP 466798]
.... similar ones
[New LWP 466765]
[Thread debugging using libthread_db enabled]
....backtrace... removed to reduce the text here

**Reply by alaa-alawi** [reply]
apology - resolved.
on a side note. now it works, but with 6 tps, not ~44.20 tok/s. how should i investigate this
